export const QUERY_SEARCH = 'SEARCH.QUERY_SEARCH';
export const AGGREGATE_RESULTS = 'SEARCH.AGGREGATE_RESULTS';
export const PAGINATE_SEARCH = 'SEARCH.PAGINATE_SEARCH';
export const TEXT_CHANGE = 'SEARCH.TEXT_CHANGE';
export const ENGINE_CHANGE = 'SEARCH.ENGINE_CHANGE';
